# Generated by Django 5.0.6 on 2024-06-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "from_country_code",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "to_country_code",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
            ],
        ),
    ]
